LivingWorldPlayerArmy
	Name = LamedonClansmenArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = LamedonClansmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LamedonClansmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LamedonClansmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LamedonClansmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorLinhirSentryArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorLinhirSentryHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorLinhirSentryHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorLinhirSentryHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorLossarnachAxemenArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = LossarnachAxeMenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LossarnachAxeMenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LossarnachAxeMenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BlackrootValeArcherArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorFighterArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorArcherArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorSpearmenArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorSpearmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorRangerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorPinnathGelinRiderArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorPinnathGelinRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorPinnathGelinRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorPinnathGelinRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorKnightArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorDolFighterArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorDolFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorDolFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorDolFighterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorKnightsofDolArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorKnightsofDolHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorFountainGuardArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorFountainGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GondorTrebuchetArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorTrebuchetLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTrebuchetLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTrebuchetLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanPeasantArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanPeasantHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanPeasantHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanPeasantHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanPeasantHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanSpearmenArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSpearmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanArcherArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanArcherNewHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanArcherNewHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanArcherNewHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanArcherNewHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanWestfolderArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanWestfolderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanWestfolderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanWestfolderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanFirienholtWardenArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanFirienholtWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanFirienholtWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanFirienholtWardenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanDoorWardenArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanDoorWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanDoorWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanDoorWardenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanHorsemenArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanHorsemenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanHorsemenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanHorsemenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanRohirrimArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanRohirrimHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanRohirrimArcherArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanRohirrimArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanSnowbournRiderArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanSnowbournRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSnowbournRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSnowbournRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanRoyalGuardMountedArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanRoyalGuardMountedHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanHelmingasArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanHelmingasWardenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanBatteringRamArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanBatteringRamLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohanMangonelArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanMangonelLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanMangonelLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanMangonelLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WestfoldPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanWestfolderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanWestfolderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RohirrimPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanRohirrimHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenAxeElfHorde_RecruitedArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenAxeElfHorde_RecruitedLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAxeElfHorde_RecruitedLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAxeElfHorde_RecruitedLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenLorienWarriorArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenLorienSentryHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienSentryHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienSentryHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenLorienArcherArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenCerinAmrothGuardArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenCerinAmrothGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenCerinAmrothGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenCerinAmrothGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LorienStalkerArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = LorienStalkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LorienStalkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LorienStalkerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GaladhrimWarriorArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = GaladhrimWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GaladhrimWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GaladhrimWarriorHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SilverTreeSentinelArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = LorienSilverTreeSentinelHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NimrodelScoutsArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenRivendellArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AmrothKnightArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenAmrothKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAmrothKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAmrothKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenHandmaidenArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = ElvenHandmaidenLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenHandmaidenLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenHandmaidenLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NandorBlademasterArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = NandorBlademasterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenEntArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = RohanEntFirLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanEntFirLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanEntFirLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElvenEntArmyAlternate
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = RohanEntBirchLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HobbitShirrifsArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TookArcherArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = TookArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = TookArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = TookArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = TookArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BreelandGuardArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ArnorBreelandGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorBreelandGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorBreelandGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BreelandRamArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ArnorBreelandRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorBreelandRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorBreelandRamLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DunedainRangersArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ArnorRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DunedainOutridersArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = RivendellDunedainOutriderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellDunedainOutriderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellDunedainOutriderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GreyCompanyArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = RivendellGreyCompanyHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RivendellGlaivemenArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ElvenRivendellInfGlaivemenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfGlaivemenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfGlaivemenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RivendellInfArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ElvenRivendellInfHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RivendellArcherArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ElvenRivendellInfArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellInfArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RivendellKnightArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = ElvenRivendellKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NoldorWarriorArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = NoldorWarriorHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RevelersArmy
	DisplayNameTag = LWA:Rivendell
	ArmyEntry
		ThingTemplate = RivendellRevelerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellRevelerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellRevelerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodRangerArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodWardenArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWardenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWardenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodSpearArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodSpearHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodOutriderArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodOutriderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodOutriderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodOutriderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodHunterArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodSilvanHunterLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodWoodmenArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = WoodmenMarksmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WoodmenMarksmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WoodmenMarksmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodWarriorArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWarriorHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodSlayerArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = GreenwoodSlayerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodSlayerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodSlayerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodArcherArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = GreenwoodArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodPalaceGuardArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodPalaceGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodPalaceGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodPalaceGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodNoblesArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = GreenwoodSindarNobleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodSindarNobleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodSindarNobleHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodDruidArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodDruidLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodDruidLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodDruidLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodBeorningArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodBeorningHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodEotheodArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodEotheodHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodGildedGuardArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodGildedGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodBatteringRamArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodBatteringRamLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodBallistaArmy
	DisplayNameTag = LWA:Mirkwood
	ArmyEntry
		ThingTemplate = MirkwoodBallistaLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodBallistaLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodBallistaLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenGuardianArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenGuardianHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGuardianHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGuardianHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenGrimHammerArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenPhalanxArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenArcherArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenVWArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenVWHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenVWHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenVWHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenUzbadulArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = KhazadUzbadulHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LaketownSpearmenArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = LaketownSpearmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DaleGuardArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DaleGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MenofDaleSwordsmanArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = MenofDaleSwordsmanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenMenOfDaleArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenMenOfDaleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenMenOfDaleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenMenOfDaleHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenEredLuinRangerArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenEredLuinRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenEredLuinTraderArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenEredLuinTraderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenEredLuinTraderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenEredLuinTraderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IronHillsWarriorArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = IronHillsWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsWarriorHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IronHillsCrossbowArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = IronHillsCrossbowHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsCrossbowHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsCrossbowHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IronHillRiderArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = IronHillRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenZerkerArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenZerkerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenBatteringRamArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarfBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarfBatteringRamLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarfBatteringRamLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenBattleWagonArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenBattleWagonNewLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenBattleWagonNewLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenBattleWagonNewLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenDemolisherArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenDemolisherLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenMangonelArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = DwarvenMangonelLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenMangonelLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenMangonelLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorFighterArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW  ;MordorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW  ;MordorFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW  ;MordorFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW  ;MordorFighterHordeLOALW
		Quantity = 1
	End	
End
LivingWorldPlayerArmy
	Name = MordorPikemanArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorArcherArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorBlackOrcArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorCentralIthilienArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorVariagArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorVariagHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorEasterlingArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorEasterlingArcherArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorEasterlingDagorlandArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorEasterlingSwordsmanArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingSwordsmanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorEasterlingKataphractArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorMountainTrollArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorDrummerTrollArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorAttackTrollArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorMorgulOrcArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorGreatBeastArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorBatteringRamArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorBatteringRamLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorCatapultArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MordorVanguardArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorVanguardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardScoutArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardFighterArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardFighterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardUrukCrossbowArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardPikemanArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardBeserkerArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardBeserkerLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardBeserkerLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardBeserkerLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardWildmanArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardWildmanSpearArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardWildmanAxeArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildmenPlayerArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardDunlandArcherArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardDunlandArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardDunlandArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardDunlandArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardDunlandAxemenArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardDunlandAxemenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardDunlandRiderArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardDunlandRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardDunlandRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardDunlandRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DunlandPlayerArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardDunlandRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardDunlandRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardDunlandHuskarlArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardDunlandHuskarlHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardMineBeserkerArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardMineBeserkerLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardFanaticArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardBerserkerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardWargPackArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWargPackHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardWargRiderArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardBallistaArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = IsengardBallistaLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardBallistaLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardBallistaLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IsengardUrukShieldbearerArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = UrukShieldbearerHordeLOALW
		Quantity = 1
		End
	ArmyEntry
		ThingTemplate = UrukShieldbearerHordeLOALW
		Quantity = 1
		End
	ArmyEntry
		ThingTemplate = UrukShieldbearerHordeLOALW
		Quantity = 1
		End
End
LivingWorldPlayerArmy
	Name = GoblinTownFighterArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = GoblinTownFighterHordeLOALW ;GoblinTownFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinTownFighterHordeLOALW ;GoblinTownFighterHordeLOALW
		Quantity = 1
	End	
End
LivingWorldPlayerArmy
	Name = GoblinFighterArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW  ;GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW  ;GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW  ;GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW  ;GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW  ;GoblinFighterHordeLOALW
		Quantity = 1
	End	
End
LivingWorldPlayerArmy
	Name = GoblinArcherArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMountainOrcSwordArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMountainOrcBruteArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMountainOrcScoutArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMarauderSwordArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMarauderSwordHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMarauderArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMarauderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildGundabadArcherArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildGundabadArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildWargPackArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildWargRiderArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildGundabadBodyGuardArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildGundabadBodyGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GoblinCaveTrollArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildAttackTrollArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildSnowTrollArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildFireDrakeArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildFireDrake_BuildableLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildGiantBatArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildGiantBatInterfaceLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGiantBatInterfaceLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGiantBatInterfaceLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildGundabadBerserkerArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildTrollSlingArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildTrollSlingLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildColdDrakeArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildColdDrakeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildMountainGiantArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MoW_CreateAHeroArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = PippinPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorPippin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BeregondPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorBeregond_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MadrilPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorMadril_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ForlongPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorForlong_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DenethorPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorDenethor_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FaramirPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorFaramir
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ImrahilPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorImrahil_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BoromirPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AragornPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorAragornMP
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GandalfPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorGandalf_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = StormCrowPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorGandalf_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LossarnachPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorForlong_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LossarnachAxeMenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IthilienPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorRangerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AnorienPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorDenethor_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorSpearmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DolAmrothPlayerArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GondorDolFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorDolFighterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MoW_CreateAHeroArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MerryPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanMerry_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = EowynPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanEowyn_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElfhelmPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanElfhelm_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ErkenbrandPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanErkenbrand
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TheodredPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanTheodred
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = EomerPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanEomer
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TheodenPlayerArmy
	DisplayNameTag = LWA:Rohan
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Elven_CreateAHeroArmy
	DisplayNameTag = LWA:Elves
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RumilPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenRumil
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = OrophinPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenOrophin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IdrialPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenIdrial_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HaldirPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenHaldir
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CelebornPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenCeleborn
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GaladrielPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenGaladrielLorien_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArwenPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenArwen_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GildorPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenGildor
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElladanPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenElladan_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElrohirPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenElrohir_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HalbaradPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ArnorHalbarad_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = StriderPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenAragorn
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GlorfindelPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenGlorfindel_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ElrondPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenElrond_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BolgerPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ArnorFattyBolger_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MaggotPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ArnorFarmerMaggot_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Mirkwood_CreateAHeroArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TaurielPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodTauriel
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GalionPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodGalion_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FerenPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodFeren
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FrumgarPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = DorwinionFrumgarLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RadagastPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodRadagast_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GrimbeornPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodGrimbeorn_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LegolasArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodLegolas
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ThranduilPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodThranduil
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ThranduilNCSPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodThranduil_NCS
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Dwarven_CreateAHeroArmy
	DisplayNameTag = LWA:Dwarves
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RoacPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenRoac_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KiliPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenKili_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FiliPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenFili_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BalinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenBalin
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CaptainofDalePlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenCaptainofDale
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenDain_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwalinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenDwalin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ThorinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenThorin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArcahPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenArcah_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GloinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenGloin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HadhodPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenHadhod_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BrandPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenBrand_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GimliPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenGimli_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = StonehelmPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenThorinStonehelm_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KingDainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenKingDain_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Mordor_CreateAHeroArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GorbagPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGorbag_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ShagratPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorShagrat_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GothmogPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGothmog
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MouthOfSauronArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorMouthOfSauron
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AkhorahilPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = UvathaPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorUvatha_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MollokPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorMollok_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KhamulPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorKhamul_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKing_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BelokhZaPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = RhunBelokhZa_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KhrenTakPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = RhunKhrenTak_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = VahRusPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = RhunVahRus_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Isengard_CreateAHeroArmy
	DisplayNameTag = LWA:Isengard
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GrishnakhArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardGrishnakh_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WormTongueArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardWormTongue_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SharkuPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSharku_WOTR
		Quantity = 1
	End	
End
LivingWorldPlayerArmy
	Name = UglukPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardUgluk
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LurtzPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WulfgarPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardWulfgar_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SarumanPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WargsPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSharku_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Wild_CreateAHeroArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MuzgashPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildMuzgash
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = UrshakPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildUrshak
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GolfimbulPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGolfimbul_WOTR
		Quantity = 1
	End
End	
LivingWorldPlayerArmy
	Name = GreatGoblinPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGreatGoblin
		Quantity = 1
	End	
End
LivingWorldPlayerArmy
	;Name = BolgPlayerArmy
	Name = LugPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		;ThingTemplate = WildBolg_WOTR
		ThingTemplate = WildLugtheMauled_WOTR
		Quantity = 1
	End
End	
LivingWorldPlayerArmy
	Name = BolgPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildBolgNew_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArnorFighterArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorFighterHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArnorArcherArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArnorRangerArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArnorKnightArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ArnorTowerShieldGuardArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorTowerShieldGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarDarkDunedainArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarDarkDunedainHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarDarkRangerArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarDarkRangerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarDireWolfArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarDireWolfHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarSnowTrollArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarSnowTrollHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarHillTrollArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarHillTrollHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarNecromancerArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarNecromancerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarThrallmasterArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarThrallMasterLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Angmar_CreateAHeroArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RogashArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarRogash
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KarshArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarKarsh
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HwaldarArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarHwaldar
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MorgramirArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarMorgramir
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WitchKingArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarWitchking
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AngmarTrollSlingArmy
	DisplayNameTag = LWA:Angmar
	ArmyEntry
		ThingTemplate = AngmarTrollSlingLOALW
		Quantity = 1
	End

End
LivingWorldPlayerArmy
	Name = Guldur_CreateAHeroArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurThrainPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurThrain_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KrimpulPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurKrimpul_WOTR
		Quantity = 1
	End
End	
LivingWorldPlayerArmy
	Name = CargastPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurCargast_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SaenathraPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurSaenathra_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurKhamulPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurKhamul_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NecromancerPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurNecromancer_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurBrokenRabbleArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurBrokenRabbleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurBrokenRabbleHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurBrokenRabbleHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurOrcGaolerArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurOrcPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurOrcPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurOrcHunterArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurOrcArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurOrcArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurFellBroodArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurFellBroodHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurTrapperArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurWoodsmenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurOrcRavagerArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurOrcRavagerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurTombGuardArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurTombGuardHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurRisenDeadArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurRisenDeadHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurHarbingerArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurHarbingerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurWightArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurUnburiedWightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurHarbingerArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurHarbingerHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurCastellanArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurCastellanLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurEntwifeArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurEntwifeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GuldurSaenathraSisterArmy
	DisplayNameTag = LWA:GuldurArmy
	ArmyEntry
		ThingTemplate = GuldurGreatSpiderLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Harad_CreateAHeroArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = CreateAHero
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BeruthielArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradBeruthiel_WOTR ;HaradBeruthiel
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SyarRhulArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradSyarRhul_WOTR ;HaradSyarRhul
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SuladanArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradSuladan
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BurodapanArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradBurodapan
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CassimirArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradCassimir
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CaranLambarArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradCaranLambar_WOTR ;HaradCaranLambar
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GoldenKingArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradGoldenKing
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HaradWarlordArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradWarlordLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlordLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlordLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlordLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradHarondorSpearmenHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = HarondorArcherHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradwaithHarondorRaiderHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradGuardsoftheSerpentHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradGuardsoftheSerpentHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradCorsairsOfUmbarHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradBlackNumenoranWarriorsHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradBlackNumenoreanVanguardHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = HaradWatchersofKarnaHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradWatchersofKarnaHordeLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = HaradMahudWarriorHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradMahudWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudWarriorHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradMahudHeadhunterHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = MahudChiefArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MahudChiefLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MahudChiefLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MahudChiefLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = HaradMumakilArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradSiegeMumakArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradSiegeMumak
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradSiegeMumak
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradSiegeMumak
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = HaradGiantScorpionArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradGiantScorpionLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradGiantScorpionLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradGiantScorpionLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HaradVultureArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradVultureLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradKaraddArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradKaraddLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradKaraddLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradKaraddLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradBeastmasterArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradBeastmasterLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBeastmasterLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBeastmasterLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradNafaratiMarauderHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradNafaratiMarauderHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradHasharinBladeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradHasharinBladeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = HaradCultistsofZigurHordeArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradCultistsofZigurHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCultistsofZigurHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCultistsofZigurHordeLOALW
		Quantity = 1
	End
End  
LivingWorldPlayerArmy
	Name = GilGaladPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = SecondAgeGilGalad_WotR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeElrondPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = SecondAgeElrond_WotR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeElendilPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = SecondAgeElendil_WotR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeGondorFighterArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeGondorArcherArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WeathertopAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeLindonWarriorArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeLindonWarriorHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeLindonArcherArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeLindonArcherHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SecondAgeLindonGuardArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeLindonGuardHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HavensAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeLindonWarriorHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeLindonArcherHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RivendellAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeLindonGuardHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeLindonGuardHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FornostAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeIsildur_WotR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceTrebuchetLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MoriaAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = KhazadGuardAdventureLAHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = KhazadGuardAdventureLAHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceDurinIV
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceDurinCustodianHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceDurinCustodianHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HithlinAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = ElvenCerinAmrothGuardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAmrothKnightHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenAmrothKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LorienAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeAmdirAdventure
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DismountedAmrothHorde_LastAllianceLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DismountedAmrothHorde_LastAllianceLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HallsAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeOropherAliveAdventure
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ErynGalenLevyHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ErynGalenLevyHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ErynGalenArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ErynGalenArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FarothAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = GreenwoodSindarNobleHordeLOALW
		Quantity = 1
	End
End           
LivingWorldPlayerArmy
	Name = OsgiliathAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeAnarion_WotR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End

End
LivingWorldPlayerArmy
	Name = IthilienAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceTrebuchetLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LastAllianceTrebuchetLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DolAmrothAllianceArmy
	DisplayNameTag = LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate = SecondAgeGondorFighterHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeGondorArcherHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeLindonWarriorHorde_WotRLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = SecondAgeLindonArcherHorde_WotRLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ForlindonAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
End 
LivingWorldPlayerArmy
	Name = OstInEdhilAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = EregionAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TharbadAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = OldForestAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GramAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = EttenmorsAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargPackHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GreyMountAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildSnowTrollHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WitheredAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = WildFireDrake_BuildableLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildFireDrake_BuildableLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildFireDrake_BuildableLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainGiantLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GundabadAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HighPassAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GoblinTownAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HighPassAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CaradhrasAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DimrillAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NMirkwoodAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HallOakAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = ForestGateAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MirkwoodAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AnduinAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GladdenAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorBlackOrcHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CelebrantAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = NCelebrantAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BrownLandsAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = GuldurKhamul_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurEntwifeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurEntwifeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurEntwifeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = EastfoldAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanAxeHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = SIthilienAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradwaithHarondorRaiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TolfalasAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BelfalasAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradGoldenKing_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = LebenninAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = HaradBlackNumenoranWarriorsHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradBlackNumenoreanVanguardHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradMahudHeadhunterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradCorsairsOfUmbarHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End

End
LivingWorldPlayerArmy
	Name = ArnenAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradHarondorSpearmenHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakil
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CrossroadsAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HarondorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MorgulAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = AndrosAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DoomAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorSauron_WotR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = GorgorothAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorWitchKing_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BlackGateAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorGreatBeastLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = MarshesAllianceArmy
	DisplayNameTag = LWA:Haradwaith

	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DagorlandAllianceArmy
	DisplayNameTag = LWA:Haradwaith
	ArmyEntry
		ThingTemplate = MordorAkhorahil_WOTR_LAS
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTrollLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMorgulOrcHorde_LASLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCatapultLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = TrueAzogPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildTrueAzog_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = PlunderersPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = MoriaHobgoblinPlundererHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MoriaHobgoblinPlundererHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Moria_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WildGreyMountainsArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcSwordHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcScoutHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = CarnDumArmy
	DisplayNameTag = LWA:CorruptedWild
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildWargRiderHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildAttackTrollLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = HighPassDOArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHordeLOALW
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = YoungThorinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = YoungThorin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenThrainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenThrain_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = YoungDainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = YoungDain_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DwarvenThrorArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenThror_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = YoungDwalinArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = YoungDwalin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = YoungBalinArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = YoungBalin_WOTR
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = DunlandDwarvenArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenEredLuinTraderHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = IronHillDwarvenArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = IronHillsWarriorHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsCrossbowHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenBattleWagonNewLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = WitheredDwarvenArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGrimHammerHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = Thrain_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGuardianHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHordeLOALW
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = BelokhzaNewPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunBelokhZa
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RazariNewPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunRazari
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = KhrenTakNewPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunKhrenTak
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunKhamulNewPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunKhamul
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = VahRusNewPlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunVahRus
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunVariagArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorVariagHorde_RhunLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunTribalArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = TribalAuxillaryHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunEasterlingSwordsmanArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingSwordsmanHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunEasterlingArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunEasterlingAxemenArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = EasterlingAxeMenHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunDragonKnightArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorDragonKnightHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunAuxillaryArcherArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = AuxillaryArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunEasterlingArcherArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunWardogsArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunWardogsHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunVariagArcherArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunVariagHorseArcherHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunKataphractArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MordorEasterlingKataphractHordeLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunChariotArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = EasterlingChariotLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunFlamesprayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunFlamesprayerLOALW
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = RhunCannonArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = RhunCannonLOALW
		Quantity = 1
	End
End